
Vagrant.configure("2") do |config|

  # Box
  config.vm.box = "ubuntu/jammy64"

  # Private network with static IP
  config.vm.network "private_network", ip: "192.168.33.10"

  # Public network
  config.vm.network "public_network", bridge: "en0: Wi-Fi"

  # Synced folder: host (local) folder "./scripts" to guest (vm) folder "/opt/scripts"
  config.vm.synced_folder "./scripts", "/opt/scripts"

  # Provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
    vb.gui = true
  end
end